#!/bin/bash

set -e
echo "Updating system packages..."
sudo apt update && sudo apt upgrade -y
echo "Installing OpenJDK21 (includes Java Development Kit and Java Runtime Environment)..."
sudo apt install -y openjdk-21-jdk # jdk / jre
echo "Installing Docker and Docker Compose..."
sudo apt install -y docker.io docker-compose
echo "Testing Docker installation"
sudo docker run hello-world
echo "Installing the project..."
./mvnw clean install
echo "Running Docker Compose..."
sudo docker-compose down -v --remove-orphans
echo "Building Docker image..."
sudo docker-compose up --build
echo "All done!"