#!/bin/bash

sudo apt update
sudo apt install -y openjdk-21-jdk # jdk / jre
#sudo snap install docker
sudo apt install -y docker-compose
sudo docker run hello-world
sudo apt install -y maven
./mvnw clean package -DskipTests
./mvnw clean install
sudo docker build -t e-shendetsia .
sudo docker-compose up --build