CREATE TABLE admin_table
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_admin_table PRIMARY KEY (id)
);

CREATE TABLE clinics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    drejtori_id BIGINT,
    address     VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    phone       VARCHAR(255)                            NOT NULL,
    website     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clinics PRIMARY KEY (id)
);

CREATE TABLE clinics_employed
(
    clinic_id   BIGINT NOT NULL,
    employed_id BIGINT NOT NULL,
    CONSTRAINT pk_clinics_employed PRIMARY KEY (clinic_id, employed_id)
);

CREATE TABLE doctor_table
(
    id         BIGINT       NOT NULL,
    profesioni VARCHAR(255) NOT NULL,
    licensa    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_doctor_table PRIMARY KEY (id)
);

CREATE TABLE employed_by
(
    clinic_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    CONSTRAINT pk_employed_by PRIMARY KEY (clinic_id, doctor_id)
);

CREATE TABLE permissions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    http_method  VARCHAR(255),
    resource_url VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE user_table
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    phone_number INTEGER                                 NOT NULL,
    salt         VARCHAR(255)                            NOT NULL,
    history      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

ALTER TABLE user_table
    ADD CONSTRAINT uc_user_table_email UNIQUE (email);

ALTER TABLE admin_table
    ADD CONSTRAINT FK_ADMIN_TABLE_ON_ID FOREIGN KEY (id) REFERENCES user_table (id);

ALTER TABLE clinics
    ADD CONSTRAINT FK_CLINICS_ON_DREJTORI FOREIGN KEY (drejtori_id) REFERENCES user_table (id);

ALTER TABLE doctor_table
    ADD CONSTRAINT FK_DOCTOR_TABLE_ON_ID FOREIGN KEY (id) REFERENCES user_table (id);

ALTER TABLE clinics_employed
    ADD CONSTRAINT fk_cliemp_on_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id);

ALTER TABLE clinics_employed
    ADD CONSTRAINT fk_cliemp_on_doctor FOREIGN KEY (employed_id) REFERENCES doctor_table (id);

ALTER TABLE employed_by
    ADD CONSTRAINT fk_empby_on_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id);

ALTER TABLE employed_by
    ADD CONSTRAINT fk_empby_on_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES user_table (id);

INSERT INTO roles (name) VALUES
                             ('DOCTOR'),
                             ('SYSTEM_ADMIN'),
                             ('PHARMACIST'),
                             ('PATIENT'),
                             ('NURSE'),
                             ('CLINIC_DIRECTOR');
