CREATE TABLE clinics
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    drejtori VARCHAR(255)                            NOT NULL,
    address  VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    phone    INTEGER                                 NOT NULL,
    website  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clinics PRIMARY KEY (id)
);

CREATE TABLE doctor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    clinic_id  BIGINT                                  NOT NULL,
    profesioni VARCHAR(255)                            NOT NULL,
    licensa    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    phone_number INTEGER                                 NOT NULL,
    salt         VARCHAR(255)                            NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);