CREATE TABLE employed_by
(
    clinic_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    CONSTRAINT pk_employed_by PRIMARY KEY (clinic_id, doctor_id)
);

CREATE TABLE permissions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    http_method  VARCHAR(255),
    resource_url VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE clinics
    ADD drejtori_id BIGINT;

ALTER TABLE users
    ADD role_id BIGINT;

ALTER TABLE clinics
    ADD CONSTRAINT FK_CLINICS_ON_DREJTORI FOREIGN KEY (drejtori_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE employed_by
    ADD CONSTRAINT fk_empby_on_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id);

ALTER TABLE employed_by
    ADD CONSTRAINT fk_empby_on_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE doctor
    DROP COLUMN clinic_id;

ALTER TABLE clinics
    DROP COLUMN drejtori;