ALTER TABLE admin_table
DROP
CONSTRAINT fk_admin_table_on_id;

ALTER TABLE clinics_employed
DROP
CONSTRAINT fk_cliemp_on_clinic;

ALTER TABLE clinics_employed
DROP
CONSTRAINT fk_cliemp_on_doctor;

ALTER TABLE clinics
DROP
CONSTRAINT fk_clinics_on_drejtori;

ALTER TABLE employed_by
DROP
CONSTRAINT fk_empby_on_clinic;

ALTER TABLE role_permissions
DROP
CONSTRAINT fk_rolper_on_permissions;

ALTER TABLE role_permissions
DROP
CONSTRAINT fk_rolper_on_role;

ALTER TABLE user_roles
DROP
CONSTRAINT fk_userol_on_role;

CREATE SEQUENCE IF NOT EXISTS allergy_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS appointment_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS bill_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS emergency_contact_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS feedback_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS history_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS insurance_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS notification_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS perscription_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS referral_table_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS test_result_table_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE allergy_table
(
    id          BIGINT       NOT NULL,
    allergen    VARCHAR(255) NOT NULL,
    extra_notes OID,
    CONSTRAINT pk_allergy_table PRIMARY KEY (id)
);

CREATE TABLE appointment_table
(
    id               BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    doctor_id        BIGINT NOT NULL,
    appointment_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason           OID,
    status           VARCHAR(255),
    CONSTRAINT pk_appointment_table PRIMARY KEY (id)
);

CREATE TABLE bill_table
(
    id          BIGINT  NOT NULL,
    user_id     BIGINT  NOT NULL,
    amount      DECIMAL NOT NULL,
    description OID     NOT NULL,
    is_paid     BOOLEAN NOT NULL,
    issued_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_bill_table PRIMARY KEY (id)
);

CREATE TABLE clinic_table
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    drejtori_id BIGINT,
    address     VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    phone       VARCHAR(255)                            NOT NULL,
    website     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clinic_table PRIMARY KEY (id)
);

CREATE TABLE emergency_contact_table
(
    id           BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    relationship VARCHAR(255),
    CONSTRAINT pk_emergency_contact_table PRIMARY KEY (id)
);

CREATE TABLE feedback_table
(
    id           BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    doctor_id    BIGINT       NOT NULL,
    message      VARCHAR(510) NOT NULL,
    rating       INTEGER,
    submitted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_feedback_table PRIMARY KEY (id)
);

CREATE TABLE history_table
(
    id          BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    doctor_id   BIGINT       NOT NULL,
    description VARCHAR(255) NOT NULL,
    diagnosis   VARCHAR(255) NOT NULL,
    treatment   VARCHAR(255) NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_history_table PRIMARY KEY (id)
);

CREATE TABLE insurance_table
(
    id               BIGINT       NOT NULL,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(255) NOT NULL,
    policy_number    VARCHAR(255) NOT NULL,
    coverage_details OID,
    active           BOOLEAN      NOT NULL,
    CONSTRAINT pk_insurance_table PRIMARY KEY (id)
);

CREATE TABLE notification_table
(
    id        BIGINT       NOT NULL,
    user_id   BIGINT       NOT NULL,
    message   VARCHAR(255) NOT NULL,
    is_read   BOOLEAN,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_notification_table PRIMARY KEY (id)
);

CREATE TABLE permission_table
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    http_method  VARCHAR(255)                            NOT NULL,
    resource_url VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permission_table PRIMARY KEY (id)
);

CREATE TABLE perscription_table
(
    id         BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    doctor_id  BIGINT       NOT NULL,
    medication VARCHAR(255) NOT NULL,
    dosage     VARCHAR(255) NOT NULL,
    frequency  VARCHAR(255),
    duration   VARCHAR(255),
    issued_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_perscription_table PRIMARY KEY (id)
);

CREATE TABLE referral_table
(
    id             BIGINT NOT NULL,
    patient_id     BIGINT NOT NULL,
    from_doctor_id BIGINT NOT NULL,
    to_doctor_id   BIGINT NOT NULL,
    reason         VARCHAR(255),
    referral_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_referral_table PRIMARY KEY (id)
);

CREATE TABLE role_table
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role_table PRIMARY KEY (id)
);

CREATE TABLE test_result_table
(
    id        BIGINT       NOT NULL,
    user_id   BIGINT       NOT NULL,
    doctor_id BIGINT       NOT NULL,
    type      VARCHAR(255) NOT NULL,
    result    VARCHAR(255) NOT NULL,
    notes     VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_test_result_table PRIMARY KEY (id)
);

CREATE TABLE user_allergy_table
(
    user_id    BIGINT       NOT NULL,
    allergy_id BIGINT       NOT NULL,
    reaction   VARCHAR(255) NOT NULL,
    notes      OID,
    "user"     BIGINT       NOT NULL,
    allergy    BIGINT       NOT NULL,
    CONSTRAINT pk_user_allergy_table PRIMARY KEY ("user", allergy)
);

ALTER TABLE doctor_table
    ADD specializimi VARCHAR(255);

ALTER TABLE doctor_table
    ALTER COLUMN specializimi SET NOT NULL;

ALTER TABLE admin_table
    ADD user_id BIGINT;

ALTER TABLE clinic_table
    ADD CONSTRAINT uc_clinic_table_email UNIQUE (email);

ALTER TABLE insurance_table
    ADD CONSTRAINT uc_f44fca98f955ea29b292c1804 UNIQUE (user_id, policy_number);

ALTER TABLE admin_table
    ADD CONSTRAINT FK_ADMIN_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE appointment_table
    ADD CONSTRAINT FK_APPOINTMENT_TABLE_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE appointment_table
    ADD CONSTRAINT FK_APPOINTMENT_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE bill_table
    ADD CONSTRAINT FK_BILL_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE clinic_table
    ADD CONSTRAINT FK_CLINIC_TABLE_ON_DREJTORI FOREIGN KEY (drejtori_id) REFERENCES user_table (id);

ALTER TABLE emergency_contact_table
    ADD CONSTRAINT FK_EMERGENCY_CONTACT_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE feedback_table
    ADD CONSTRAINT FK_FEEDBACK_TABLE_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE feedback_table
    ADD CONSTRAINT FK_FEEDBACK_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE history_table
    ADD CONSTRAINT FK_HISTORY_TABLE_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE history_table
    ADD CONSTRAINT FK_HISTORY_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE insurance_table
    ADD CONSTRAINT FK_INSURANCE_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE notification_table
    ADD CONSTRAINT FK_NOTIFICATION_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE perscription_table
    ADD CONSTRAINT FK_PERSCRIPTION_TABLE_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE perscription_table
    ADD CONSTRAINT FK_PERSCRIPTION_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE referral_table
    ADD CONSTRAINT FK_REFERRAL_TABLE_ON_FROM_DOCTOR FOREIGN KEY (from_doctor_id) REFERENCES doctor_table (id);

ALTER TABLE referral_table
    ADD CONSTRAINT FK_REFERRAL_TABLE_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES user_table (id);

ALTER TABLE referral_table
    ADD CONSTRAINT FK_REFERRAL_TABLE_ON_TO_DOCTOR FOREIGN KEY (to_doctor_id) REFERENCES doctor_table (id);

ALTER TABLE test_result_table
    ADD CONSTRAINT FK_TEST_RESULT_TABLE_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_table (id);

ALTER TABLE test_result_table
    ADD CONSTRAINT FK_TEST_RESULT_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE user_allergy_table
    ADD CONSTRAINT FK_USER_ALLERGY_TABLE_ON_ALLERGY FOREIGN KEY (allergy_id) REFERENCES allergy_table (id);

ALTER TABLE user_allergy_table
    ADD CONSTRAINT FK_USER_ALLERGY_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE employed_by
    ADD CONSTRAINT fk_empby_on_clinic FOREIGN KEY (clinic_id) REFERENCES clinic_table (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permission_id) REFERENCES permission_table (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES role_table (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role_table (id);

DROP TABLE clinics CASCADE;

DROP TABLE clinics_employed CASCADE;

DROP TABLE permissions CASCADE;

DROP TABLE roles CASCADE;

ALTER TABLE admin_table
DROP
COLUMN id;

ALTER TABLE doctor_table
DROP
COLUMN profesioni;

ALTER TABLE admin_table
    ADD CONSTRAINT pk_admin_table PRIMARY KEY (user_id);